version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: trivia_app
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/cable.yml:/app/config/cable.yml
    environment:
      REDIS_URL: redis://redis:6379/1

  sidekiq:
    image: trivia_app
    command: bin/sidekiq
    env_file: .env
    depends_on:
      - web
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/cable.yml:/app/config/cable.yml
    environment:
      REDIS_URL: redis://redis:6379/1

  db:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379

  frontend:
    image: trivia_app
    command: bin/rails tailwindcss:watch
    env_file: .env
    tty: true
    volumes:
      - .:/app

  rails:
    image: trivia_app
    entrypoint: bin/rails
    env_file: .env
    profiles: ["tools"]
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
    depends_on:
      - db

volumes:
  pgdata:
  test-pgdata:
